function dydt = FootTrajGenZder(t)
%FOOTTRAJGENZDER
%    DYDT = FOOTTRAJGENZDER(T)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    02-Oct-2014 15:09:30

t2 = t-1.0;
dydt = t.^2.*t2.^2.*(t.*2.0-1.0).*(-9.6e1./5.0);
