function dxdt = FootTrajGenXder(t)
%FOOTTRAJGENXDER
%    DXDT = FOOTTRAJGENXDER(T)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    02-Oct-2014 15:09:29

t2 = t-1.0;
dxdt = t.^2.*t2.^2.*3.0;
