function ddydt = FootTrajGenZder2(t)
%FOOTTRAJGENZDER2
%    DDYDT = FOOTTRAJGENZDER2(T)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    02-Oct-2014 11:34:47

t2 = t.^2;
ddydt = t.*(t.*6.0-t2.*1.0e1+t.*t2.*5.0-1.0).*(-1.92e2./5.0);
