function y = FootTrajGenZ(t)
%FOOTTRAJGENZ
%    Y = FOOTTRAJGENZ(T)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    21-Sep-2014 15:43:50

t2 = t.^2;
t3 = t-1.0;
t4 = t3.^2;
y = t.*t2.*t3.*t4.*(-3.2e1./5.0);
