function ddxdt = FootTrajGenXder2(t)
%FOOTTRAJGENXDER2
%    DDXDT = FOOTTRAJGENXDER2(T)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    02-Oct-2014 15:09:29

ddxdt = t.*(t.*-3.0+t.^2.*2.0+1.0).*6.0;
