function x = my_function(a1,a2,a3,a4,a5,a6,t)
%MY_FUNCTION
%    X = MY_FUNCTION(A1,A2,A3,A4,A5,A6,T)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    10-Jul-2014 16:00:50

t2 = t.^2;
t3 = t2.^2;
x = a1+a2.*t+a3.*t2+a5.*t3+a4.*t.*t2+a6.*t.*t3;
