function dxdt = ZMPTrajGenXder_v2(t)
%ZMPTRAJGENXDER_V2
%    DXDT = ZMPTRAJGENXDER_V2(T)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    21-Sep-2014 15:43:51

t2 = t.^2;
t3 = t2.^2;
dxdt = t.*(-4.517151211015788e-2)+t2.*5.180258293908251e-1+t3.*5.684417310371306e-1-t.*t2.*8.435374874640138e-1-t.*t3.*1.723473640243738e-1+t2.*t3.*1.932156855590763e-2+4.201384018174989e-16;
