function ddxdt = ZMPTrajGenXder2_v2(t)
%ZMPTRAJGENXDER2_V2
%    DDXDT = ZMPTRAJGENXDER2_V2(T)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    21-Sep-2014 15:43:51

t2 = t.^2;
t3 = t2.^2;
ddxdt = t.*1.03605165878165-t2.*2.530612462392041-t3.*8.617368201218691e-1+t.*t2.*2.273766924148522+t.*t3.*1.159294113354458e-1-4.517151211015788e-2;
